// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQkmB1jxB4vaozB_ZGvIwYhm-dtt_jqiI',
    appId: '1:781898936345:web:65568068a8fd7ddd92fa88',
    messagingSenderId: '781898936345',
    projectId: 'thingstodo-92657',
    authDomain: 'thingstodo-92657.firebaseapp.com',
    storageBucket: 'thingstodo-92657.firebasestorage.app',
    databaseURL: 'https://thingstodo-92657-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwao_VaznlQyfG9-ImewRXDZrvT_sg3bg',
    appId: '1:781898936345:android:2ea96ba43d546a1892fa88',
    messagingSenderId: '781898936345',
    projectId: 'thingstodo-92657',
    storageBucket: 'thingstodo-92657.firebasestorage.app',
    databaseURL: 'https://thingstodo-92657-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLRQ3IplM6uylvF_gbABinxo9kSpJDnY4',
    appId: '1:781898936345:ios:424cb091c6c58c4992fa88',
    messagingSenderId: '781898936345',
    projectId: 'thingstodo-92657',
    storageBucket: 'thingstodo-92657.firebasestorage.app',
    iosBundleId: 'com.example.flutterCac',
    databaseURL: 'https://thingstodo-92657-default-rtdb.firebaseio.com',
  );
}
